import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
    "./app/**/*.{js,ts,jsx,tsx}",
    "./src/app/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        roboto: ["Roboto Condensed", "sans-serif"],
      },
      colors: {
        ds: {
          text: "#b6c2cf",
          textDisabled: "#bfdbf847",
          textInverse: "#1d2125",
          textSelected: "#579dff",
          textBrand: "#579dff",
          textDanger: "#fd9891",
          textWarning: "#f5cd47",
          textWarningInverse: "#1d2125",
          textSuccess: "#7ee2b8",
          textDiscovery: "#b8acf6",
          textInformation: "#85b8ff",
          textSubtlest: "#8c9bab",
          textSubtle: "#9fadbc",
          icon: "#9fadbc",
          iconDisabled: "#bfdbf847",
          iconInverse: "#1d2125",
          iconSelected: "#579dff",
          iconBrand: "#579dff",
          iconDanger: "#f15b50",
          iconWarning: "#f5cd47",
          iconWarningInverse: "#1d2125",
          iconSuccess: "#2abb7f",
          iconDiscovery: "#8f7ee7",
          iconInformation: "#388bff",
          iconSubtle: "#8c9bab",
          border: "#a6c5e229",
          borderDisabled: "#a1bdd914",
          borderFocused: "#85b8ff",
          borderInput: "#738496",
          borderInverse: "#161a1d",
          borderSelected: "#579dff",
          borderBrand: "#579dff",
          borderDanger: "#f15b50",
          borderWarning: "#cf9f02",
          borderSuccess: "#2abb7f",
          borderDiscovery: "#8f7ee7",
          borderInformation: "#388bff",
          borderBold: "#738496",
          backgroundDisabled: "#bcd6f00a",
          backgroundInput: "#22272b",
          backgroundInputHovered: "#282e33",
          backgroundInputPressed: "#22272b",
          backgroundInverseSubtle: "#ffffff29",
          backgroundInverseSubtleHovered: "#ffffff3d",
          backgroundInverseSubtlePressed: "#ffffff52",
          backgroundNeutral: "#a1bdd914",
          backgroundNeutralHovered: "#a6c5e229",
          backgroundNeutralPressed: "#bfdbf847",
          backgroundNeutralSubtle: "#0000",
          backgroundNeutralSubtleHovered: "#a1bdd914",
          backgroundNeutralSubtlePressed: "#a6c5e229",
          backgroundNeutralBold: "#9fadbc",
          backgroundNeutralBoldHovered: "#b6c2cf",
          backgroundNeutralBoldPressed: "#c7d1db",
          backgroundSelected: "#1c2b41",
          backgroundSelectedHovered: "#09326c",
          backgroundSelectedPressed: "#05c",
          backgroundSelectedBold: "#579dff",
          backgroundSelectedBoldHovered: "#85b8ff",
          backgroundSelectedBoldPressed: "#cce0ff",
          backgroundBrandSubtlest: "#1c2b41",
          backgroundBrandSubtlestHovered: "#09326c",
          backgroundBrandSubtlestPressed: "#05c",
          backgroundBrandBold: "#579dff",
          backgroundBrandBoldHovered: "#85b8ff",
          backgroundBrandBoldPressed: "#cce0ff",
          backgroundBrandBoldest: "#e9f2ff",
          backgroundBrandBoldestHovered: "#cce0ff",
          backgroundBrandBoldestPressed: "#85b8ff",
          backgroundDanger: "#42221f",
          backgroundDangerHovered: "#5d1f1a",
          backgroundDangerPressed: "#ae2e24",
          backgroundDangerBold: "#f87168",
          backgroundDangerBoldHovered: "#fd9891",
          backgroundDangerBoldPressed: "#ffd5d2",
          backgroundWarning: "#332e1b",
          backgroundWarningHovered: "#533f04",
          backgroundWarningPressed: "#7f5f01",
          backgroundWarningBold: "#f5cd47",
          backgroundWarningBoldHovered: "#e2b203",
          backgroundWarningBoldPressed: "#cf9f02",
          backgroundSuccess: "#1c3329",
          backgroundSuccessHovered: "#164b35",
          backgroundSuccessPressed: "#216e4e",
          backgroundSuccessBold: "#4bce97",
          backgroundSuccessBoldHovered: "#7ee2b8",
          backgroundSuccessBoldPressed: "#baf3db",
          backgroundDiscovery: "#2b273f",
          backgroundDiscoveryHovered: "#352c63",
          backgroundDiscoveryPressed: "#5e4db2",
          backgroundDiscoveryBold: "#9f8fef",
          backgroundDiscoveryBoldHovered: "#b8acf6",
          backgroundDiscoveryBoldPressed: "#dfd8fd",
          backgroundInformation: "#1c2b41",
          backgroundInformationHovered: "#09326c",
          backgroundInformationPressed: "#05c",
          backgroundInformationBold: "#579dff",
          backgroundInformationBoldHovered: "#85b8ff",
          backgroundInformationBoldPressed: "#cce0ff",
          blanket: "#10121499",
          blanketSelected: "#1d7afc14",
          blanketDanger: "#e3493514",
          interactionHovered: "#fff3",
          interactionPressed: "#ffffff5c",
          skeleton: "#a1bdd914",
          skeletonSubtle: "#bcd6f00a",
          surface: "#1d2125",
          surfaceHovered: "#22272b",
          surfacePressed: "#282e33",
          surfaceOverlay: "#0f1926",
          surfaceOverlayHovered: "#2c333a",
          surfaceOverlayPressed: "#38414a",
          surfaceRaised: "#22272b",
          surfaceRaisedHovered: "#282e33",
          surfaceRaisedPressed: "#2c333a",
          surfaceSunken: "#161a1d",
          shadowOverflow:
            "0px 0px 12px #0304048f, 0px 0px 1px #03040480",
          shadowOverflowPerimeter: "#03040480",
          shadowOverflowSpread: "#0304048f",
          shadowOverlay:
            "0px 0px 0px 1px #39424a, 0px 8px 12px #0304045c, 0px 0px 1px 1px #03040480",
          shadowRaised:
            "0px 0px 0px 1px #0000, 0px 1px 1px #03040480, 0px 0px 1px #03040480",
          opacityDisabled: "0.4",
          opacityLoading: "0.2",
          UNSAFETransparent: "transparent",
          elevationSurfaceCurrent: "#1d2125",
        },
      },
    },
  },
  plugins: [],
} satisfies Config;